config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('schedule/', include('schedule.urls')),
    path('admin/', admin.site.urls),
]

schedule/urls.py
from django.urls import path, register_converter

from . import views, converters

register_converter(converters.DateConverter, 'date')

app_name = 'schedule'
urlpatterns = [
    path('<date:date>/', views.schedule, name='schedule'),
    path('<date:date>/submit', views.submit_pickup, name='submit_pickup'),
    path('<date:date>/remove', views.submit_pickup_removal, name='submit_pickup_removal'),
]

schedule/models.py
from django.db import models

# Create your models here.

class PickupDate(models.Model):
    date = models.DateField('date of pickup', unique=True)

    def __str__(self):
        return str(self.date)

class Timeslot(models.Model):
    start = models.TimeField('start of timeslot')
    # open-ended for now

    def __str__(self):
        return self.start.isoformat(timespec='minutes')

    class Meta:
        ordering = ['start']

class Member(models.Model):
    member_number = models.PositiveIntegerField(
        verbose_name='aoff member number',
        blank=True,
        null=True,
    )

class Pickup(models.Model):
    date = models.ForeignKey(PickupDate, on_delete=models.CASCADE)
    time = models.ForeignKey(Timeslot, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)

schedule/views.py
from django.shortcuts import get_object_or_404, render
from .models import *
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse

def schedule(request, date):
    date = get_object_or_404(PickupDate, date=date)
    member_number = request.POST and request.POST.get('member_number') \
            or None
    member_id = request.session.get('member_id')
    if member_id is not None:
        member = get_object_or_404(Member, pk=member_id)
    elif member_number:
        member = Member()
        request.session['member_id'] = member.id
        request.session.set_expiry(0)
    else:
        member = None
    if member_number and member.member_number != member_number:
        member.member_number = member_number
        member.save()
    timeslots = Timeslot.objects.all()
    for timeslot in timeslots:
        timeslot.sum = len(Pickup.objects.filter(time=timeslot))
        if member:
            try:
                timeslot.own_pickup = \
                        Pickup.objects.filter(
                                date=date,
                                time=timeslot,
                                member=member,
                        ).exists()
            except Pickup.DoesNotExist:
                timeslot.own_pickup = False
        else:
            timeslot.own_pickup = False

    return render(request, 'schedule/schedule.html',
            { 'date': date,
                'timeslots': timeslots,
                })

def submit_pickup(request, date):
    date = get_object_or_404(PickupDate, date=date)
    request.session.set_expiry(0)
    member_id = request.session.get('member_id')
    if not member_id:
        member = Member(member_number=request.POST.get('member_number'))
        member.save()
        request.session['member_id'] = member.id
    else:
        member = get_object_or_404(Member, pk=member_id)
    timeslot = get_object_or_404(Timeslot, pk=request.POST.get('timeslot'))
    Pickup(date=date, time=timeslot, member=member).save()
    return HttpResponseRedirect(reverse('schedule:schedule', args=(date.date,)))

def submit_pickup_removal(request, date):
    date = get_object_or_404(PickupDate, date=date)
    member = get_object_or_404(Member, pk=request.session.get('member_id'))
    timeslot = get_object_or_404(Timeslot, pk=request.POST.get('timeslot'))
    Pickup.objects.filter(date=date, time=timeslot, member=member).delete()
    return HttpResponseRedirect(reverse('schedule:schedule', args=(date.date,)))

schedule/templates/schedule/schedule.html
<!DOCTYPE html>
<title>AOFF</title>

<h1>Afhentningstidsplan</h1>
<p>For at minimere kødannelse bedes medlemmer der skal afhente grøntsager om at vælge hvornår de har tænkt sig at afhente sine grøntsager.
Det er hverken bindende eller et krav, men blot en hjælp til vores medlemmer så I kan planlægge afhentning når der er få der skal hente.</p>
<p>Det foregår anonymt - andre kan ikke se hvem der henter hvornår.
Vi gemmer en såkaldt 'cookie' i din browser med det eneste formål så hvis du kommer tilbage til siden senere i samme browser kan du opdatere eller fjerne dit valgte afhentningstidspunkt.
Bemærk at du <em>ikke</em> kan ændre afhentningstidspunkt fra en anden browser eller hvis cookien bliver fjernet.
Du kan skrive dit medlemsnummer for at hjælpe administratorer i at rette dine afhentningstidspunkter, men det er <em>ikke</em> et krav.</p>

<h2>Afhentning {{ date }}</h2>
<form action="{% url 'schedule:schedule' date.date %}" method="POST">
  {% csrf_token %}
  <label for="member_number">Medlemsnummer (ikke obligatorisk)</label>
  <input min="0" type="number" placeholder="Mit medlemsnummer" name="member_number" id="member_number" />

  <table>
    <thead><tr>
        <th>Tidspunkt</th>
        <th>Registrerede afhentninger</th>
        <th></th> {# Action #}
      </tr>
    </thead>
  {% for timeslot in timeslots %}
  <tr>
    <td>{{ timeslot.start | time:"H:i" }}</td>
    <td>{{ timeslot.sum }} {% if timeslot.own_pickup %}(inklusiv dig){% endif %}</td>
    <td>{% if timeslot.own_pickup %}
      <button name="timeslot" value="{{ timeslot.pk }}" formaction="{% url 'schedule:submit_pickup_removal' date.date %}">Fravælg</button>
      {% else %}
      <button name="timeslot" value="{{ timeslot.pk }}" formaction="{% url 'schedule:submit_pickup' date.date %}">Vælg</button>
      {% endif %}
  </tr>
  {% endfor %}
  </table>
</form>